-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'ORGANIZATION_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'ENVIRONMENT_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'ENVIRONMENT_DELETED';

-- AlterTable
ALTER TABLE "organizations" ADD COLUMN "description" TEXT;

-- AlterTable
ALTER TABLE "environments" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
